#Swarm mode deployment:
#https://docs.docker.com/engine/swarm/stack-deploy/

services:
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    ports:
      - 9090:9090
    restart: unless-stopped
    volumes:
      - ./prometheus:/etc/prometheus
        #- prom_data:/prometheus
      - cif-volume:/prometheus
  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - 3000:3000
    restart: unless-stopped
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=grafana
    volumes:
      - ./grafana:/etc/grafana/provisioning/datasources
volumes:
  prom_data:
  cif-volume:  
    driver_opts:
      type: cifs
      o: "username=docker,password=123456,file_mode=0777,dir_mode=0777,vers=3.0"
      device: "//192.168.1.212/dockershare"
